// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userDataFieldNames          = builder.RawFieldNames(&UserData{})
	userDataRows                = strings.Join(userDataFieldNames, ",")
	userDataRowsExpectAutoSet   = strings.Join(stringx.Remove(userDataFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userDataRowsWithPlaceHolder = strings.Join(stringx.Remove(userDataFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGoZeroUserDataIdPrefix = "cache:goZero:userData:id:"
)

type (
	userDataModel interface {
		TransInsert(ctx context.Context, session sqlx.Session, data *UserData) (sql.Result, error)
		Insert(ctx context.Context, data *UserData) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserData, error)
		Update(ctx context.Context, data *UserData) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserDataModel struct {
		sqlc.CachedConn
		table string
	}

	UserData struct {
		Id     int64  `db:"id"`
		Data   string `db:"data"`
		UserId int64  `db:"user_id"`
	}
)

func newUserDataModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserDataModel {
	return &defaultUserDataModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_data`",
	}
}

func (m *defaultUserDataModel) Delete(ctx context.Context, id int64) error {
	goZeroUserDataIdKey := fmt.Sprintf("%s%v", cacheGoZeroUserDataIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, goZeroUserDataIdKey)
	return err
}

func (m *defaultUserDataModel) FindOne(ctx context.Context, id int64) (*UserData, error) {
	goZeroUserDataIdKey := fmt.Sprintf("%s%v", cacheGoZeroUserDataIdPrefix, id)
	var resp UserData
	err := m.QueryRowCtx(ctx, &resp, goZeroUserDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userDataRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserDataModel) TransInsert(ctx context.Context, session sqlx.Session, data *UserData) (sql.Result, error) {
	goZeroUserDataIdKey := fmt.Sprintf("%s%v", cacheGoZeroUserDataIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userDataRowsExpectAutoSet)
		return session.ExecCtx(ctx, query, data.Id, data.Data, data.UserId)
	}, goZeroUserDataIdKey)
	return ret, err
}

func (m *defaultUserDataModel) Insert(ctx context.Context, data *UserData) (sql.Result, error) {
	goZeroUserDataIdKey := fmt.Sprintf("%s%v", cacheGoZeroUserDataIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userDataRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Data, data.UserId)
	}, goZeroUserDataIdKey)
	return ret, err
}

func (m *defaultUserDataModel) Update(ctx context.Context, data *UserData) error {
	goZeroUserDataIdKey := fmt.Sprintf("%s%v", cacheGoZeroUserDataIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userDataRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Data, data.UserId, data.Id)
	}, goZeroUserDataIdKey)
	return err
}

func (m *defaultUserDataModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGoZeroUserDataIdPrefix, primary)
}

func (m *defaultUserDataModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userDataRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserDataModel) tableName() string {
	return m.table
}
