// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CreateUserReq struct {
	Mobile string `json:"mobile"`
	Name   string `json:"name"'`
}

type CreateUserResp struct {
	Flag bool `json:"flag"`
}

type GetUserInfoReq struct {
	Id int64 `form:"id"`
}

type GetUserInfoResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type UpdateUserReq struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type UpdateUserResp struct {
	Flag bool `json:"flag"`
}
