// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"zero-study/api/demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TestMiddleware},
			[]rest.Route{
				{
					// 创建用户
					Method:  http.MethodPost,
					Path:    "/user/create",
					Handler: userCreateHandler(serverCtx),
				},
				{
					// 获取用户信息
					Method:  http.MethodGet,
					Path:    "/user/info",
					Handler: userInfoHandler(serverCtx),
				},
				{
					// 修改用户信息
					Method:  http.MethodPost,
					Path:    "/user/update",
					Handler: userUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/userapi/v1"),
	)
}
